### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by cdutra** [aliyun/bosh-alicloud-cpi-release#2]
## Integration Tests

1. As a user I can upload a stemcell (light)
  - create_stemcell

2. As a user I can delete a stemcell (light)
  - delete_stemcell

3. As a user I can create a VM
  - create_vm
  - set_vm_metadata (optional)

3. As a user I can delete a VM
  - delete_vm

4. As a user I can create a VM with a persistent disk
  - create_vm
  - set_vm_metadata (optional)
  - create_disk
  - set_disk_metadata (optional)
  - attach_disk

5. As a user I can update a VM with a persistent disk
  - detach_disk
  - delete_vm
  - create_vm
  - attach_disk

6. As a user I can delete a persistent disk
  - has_disk
  - delete_disk

**Comment by ailan-gl** [comment]
Integration Tests implemented in release 8.
